# Generated by Django 5.1.5 on 2025-11-14 22:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id_nomina', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('periodo_inicio', models.DateField(verbose_name='Período de Inicio')),
                ('periodo_fin', models.DateField(verbose_name='Período de Fin')),
                ('tipo_periodo', models.CharField(max_length=50, verbose_name='Tipo de Período')),
                ('total_asignaciones_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Asignaciones (Bs)')),
                ('total_deducciones_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Deducciones (Bs)')),
                ('sueldo_neto_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sueldo Neto (Bs)')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_depa', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_contratacion', models.DateField()),
                ('id_depa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_trabajo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosNomina',
            fields=[
                ('id_parametro', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('tasa_ivss', models.DecimalField(decimal_places=4, default=Decimal('0.0400'), max_digits=5, verbose_name='Tasa IVSS (Ej: 0.04)')),
                ('tasa_rpe', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), max_digits=5, verbose_name='Tasa REPO/INCE (Ej: 0.01)')),
                ('tasa_faov', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), max_digits=5, verbose_name='Tasa FAOV (Ej: 0.02)')),
                ('unidad_tributaria_valor', models.DecimalField(decimal_places=2, default=Decimal('43.00'), max_digits=10, verbose_name='Valor de la Unidad Tributaria (Bs)')),
                ('factor_calculo_cestaticket', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, verbose_name='Factor Diario Cestaticket (Ej: 8)')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Parámetro de Nómina',
                'verbose_name_plural': 'Parámetros de Nómina',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasa',
            fields=[
                ('id_tasa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('valor_tasa', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeJornada',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jornada', models.CharField(max_length=100)),
                ('horas_semanales', models.IntegerField()),
                ('sueldo_semanal_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id_nomina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='secundario.nomina', verbose_name='Nómina')),
                ('sueldo_bs_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Sueldo Base (Bs)')),
                ('cestaticket_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Cestaticket (Bs)')),
                ('horas_ordinarias', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Horas Ordinarias')),
                ('horas_extras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Total Horas Extras')),
                ('pago_horas_extras_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Pago Horas Extras (Bs)')),
                ('horas_festivas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Total Horas Festivas')),
                ('pago_horas_festivas_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Pago Horas Festivas (Bs)')),
                ('dias_vacaciones', models.IntegerField(default=0, verbose_name='Días de Vacaciones Pagados')),
                ('dias_enfermedad', models.IntegerField(default=0, verbose_name='Días de Inasistencia (Deducidos)')),
                ('ivss_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Deducción IVSS (Bs)')),
                ('rpe_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Deducción RPE (Bs)')),
                ('faov_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Deducción FAOV (Bs)')),
                ('pago_inasistencias_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Deducción Inasistencias (Bs)')),
                ('pago_prestamo_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Deducción Préstamo (Bs)')),
                ('total_asignaciones_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Asignaciones')),
                ('total_deducciones_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Deducciones')),
            ],
            options={
                'verbose_name': 'Concepto de Nómina',
                'verbose_name_plural': 'Conceptos de Nómina',
            },
        ),
        migrations.AddField(
            model_name='nomina',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado', verbose_name='Empleado'),
        ),
        migrations.CreateModel(
            name='SueldoLabor',
            fields=[
                ('id_labor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='secundario.labor', verbose_name='Labor (Cargo)')),
                ('sueldo_base_semanal_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Sueldo Base Semanal (USD)')),
                ('fecha_establecimiento', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sueldo por Labor',
                'verbose_name_plural': 'Sueldos por Labor',
            },
        ),
        migrations.AddField(
            model_name='nomina',
            name='id_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.labor', verbose_name='Labor'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.labor'),
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin_relacion', models.DateField(verbose_name='Fecha de Fin de Relación Laboral')),
                ('motivo_terminacion', models.CharField(choices=[('renuncia', 'Renuncia'), ('despido_justificado', 'Despido Justificado'), ('despido_injustificado', 'Despido Injustificado'), ('vacaciones', 'Vacaciones')], max_length=50, verbose_name='Motivo de Terminación')),
                ('salario_normal_final', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Último Salario Normal')),
                ('salario_integral_final', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Último Salario Integral')),
                ('monto_prestaciones_garantia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Garantía de Prestaciones Sociales')),
                ('monto_intereses_prestaciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Intereses de Prestaciones')),
                ('monto_prestaciones_retroactivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Prestaciones (Cálculo Retroactivo)')),
                ('monto_prestaciones_a_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Prestaciones a Pagar')),
                ('anticipos_prestaciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Anticipos de Prestaciones Descontados')),
                ('dias_vacaciones_otorgados', models.IntegerField(blank=True, null=True, verbose_name='Días de Vacaciones Otorgados (si aplica)')),
                ('fecha_regreso_trabajo', models.DateField(blank=True, null=True, verbose_name='Fecha de Regreso al Trabajo')),
                ('dias_vacaciones_pendientes', models.IntegerField(default=0, verbose_name='Días Vacaciones Pendientes')),
                ('monto_vacaciones_pendientes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Vacaciones Pendientes')),
                ('dias_bono_vacacional_pendiente', models.IntegerField(default=0, verbose_name='Días Bono Vacacional Pendientes')),
                ('monto_bono_vacacional_pendiente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Bono Vacacional Pendiente')),
                ('dias_utilidades_pendientes', models.IntegerField(default=0, verbose_name='Días Utilidades Pendientes')),
                ('monto_utilidades_pendientes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Utilidades Pendientes')),
                ('monto_indemnizacion_despido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Indemnización por Despido Injustificado')),
                ('monto_preaviso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto de Preaviso')),
                ('total_liquidacion', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total de Liquidación')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='secundario.empleado')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-fecha_fin_relacion'],
            },
        ),
        migrations.CreateModel(
            name='PrestacionSocialAcumulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateField(default=django.utils.timezone.now)),
                ('monto_acumulado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('intereses_acumulados', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('dias_acumulados', models.IntegerField(default=0)),
                ('salario_integral_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones_acumuladas', to='secundario.empleado')),
            ],
            options={
                'verbose_name': 'Prestación Social Acumulada',
                'verbose_name_plural': 'Prestaciones Sociales Acumuladas',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('monto_total_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Total del Préstamo (Bs)')),
                ('monto_pendiente_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Pendiente (Bs)')),
                ('cuotas_restantes', models.IntegerField(default=0, verbose_name='Cuotas Restantes')),
                ('monto_cuota_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto por Cuota (Bs)')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.profesion'),
        ),
        migrations.CreateModel(
            name='Sueldo',
            fields=[
                ('id_sueldo', models.AutoField(primary_key=True, serialize=False)),
                ('sueldo_usd_referencia', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('sueldo_bs', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado', verbose_name='Empleado')),
                ('id_labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.labor', verbose_name='Labor')),
                ('id_tasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.tasa', verbose_name='Tasa')),
            ],
            options={
                'verbose_name': 'Sueldo Liquidado (Histórico)',
                'verbose_name_plural': 'Sueldos Liquidados (Históricos)',
            },
        ),
        migrations.AddField(
            model_name='nomina',
            name='id_sueldo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.sueldo', verbose_name='Sueldo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.tipodejornada'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=100)),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='secundario.empleado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asistenciaconfirmada',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('asistio', models.BooleanField(default=False)),
                ('fecha_asistencia', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado')),
            ],
            options={
                'unique_together': {('id_empleado', 'fecha_asistencia', 'asistio')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField(verbose_name='Fecha de Asistencia')),
                ('asistio', models.BooleanField(default=False, verbose_name='Asistió')),
                ('tipo_inasistencia', models.CharField(blank=True, choices=[('justificada', 'Justificada'), ('injustificada', 'Injustificada'), ('enfermedad', 'Enfermedad'), ('vacaciones', 'Vacaciones'), ('permiso', 'Permiso')], max_length=20, null=True, verbose_name='Tipo de inasistencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('id_empleado', 'fecha_asistencia')},
            },
        ),
    ]
