# Generated by Django 5.1.5 on 2025-07-04 18:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_depa', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_trabajo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasa',
            fields=[
                ('id_tasa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('valor_tasa', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeJornada',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jornada', models.CharField(max_length=100)),
                ('horas_semanales', models.IntegerField()),
                ('sueldo_semanal_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_contratacion', models.DateField()),
                ('id_depa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.departamento')),
                ('id_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.labor')),
                ('id_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.profesion')),
                ('id_jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.tipodejornada')),
            ],
        ),
        migrations.CreateModel(
            name='Sueldo',
            fields=[
                ('id_sueldo', models.AutoField(primary_key=True, serialize=False)),
                ('sueldo_bs', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado', verbose_name='Empleado')),
                ('id_tasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.tasa', verbose_name='Tasa')),
                ('id_jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.tipodejornada', verbose_name='Jornada')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id_nomina', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_inicio', models.DateField(verbose_name='Fecha de Inicio del Período')),
                ('periodo_fin', models.DateField(verbose_name='Fecha de Fin del Período')),
                ('tipo_periodo', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='quincenal', max_length=10)),
                ('sueldo_bs_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cestaticket_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('horas_extras', models.IntegerField(default=0)),
                ('horas_ordinarias', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pago_horas_extras_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('horas_festivas', models.IntegerField(default=0)),
                ('pago_horas_festivas_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dias_vacaciones', models.IntegerField(default=0)),
                ('dias_enfermedad', models.IntegerField(default=0)),
                ('total_asignaciones_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ivss_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rpe_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('faov_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_deducciones_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sueldo_neto_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado')),
                ('id_sueldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.sueldo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asistenciaconfirmada',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('asistio', models.BooleanField(default=False)),
                ('fecha_asistencia', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado')),
            ],
            options={
                'unique_together': {('id_empleado', 'fecha_asistencia', 'asistio')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField(verbose_name='Fecha de Asistencia')),
                ('asistio', models.BooleanField(default=False, verbose_name='Asistió')),
                ('tipo_inasistencia', models.CharField(blank=True, choices=[('justificada', 'Justificada'), ('injustificada', 'Injustificada'), ('enfermedad', 'Enfermedad'), ('vacaciones', 'Vacaciones'), ('permiso', 'Permiso')], max_length=20, null=True, verbose_name='Tipo de inasistencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('id_empleado', 'fecha_asistencia')},
            },
        ),
    ]
