# Generated by Django 5.1.5 on 2025-11-18 21:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodejornada',
            name='horas_semanales',
        ),
        migrations.RemoveField(
            model_name='tipodejornada',
            name='sueldo_semanal_usd',
        ),
        migrations.AddField(
            model_name='tipodejornada',
            name='horas_diarias',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, verbose_name='Horas Diarias de Trabajo'),
        ),
    ]
