# Generated by Django 5.1.5 on 2025-07-05 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='id_trabajo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secundario.labor'),
            preserve_default=False,
        ),
    ]
