# Generated by Django 5.1.5 on 2025-04-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sueldo',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado'),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='id_jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.tipodejornada'),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='id_tasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.tasa'),
        ),
    ]
