# Generated by Django 5.1.5 on 2025-07-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liquidacion',
        ),
    ]
