# Generated by Django 5.1.5 on 2025-07-16 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0002_nomina_id_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='empleado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='secundario.empleado'),
        ),
    ]
