# Generated by Django 5.1.5 on 2025-07-24 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0002_delete_liquidacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id_liquidacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_liquidacion', models.DateField(default=django.utils.timezone.now)),
                ('tipo_liquidacion', models.CharField(choices=[('DESPIDO', 'Despido'), ('RENUNCIA', 'Renuncia'), ('JUBILACION', 'Jubilación'), ('VACACIONES', 'Pago de Vacaciones'), ('LIQUIDACION', 'Liquidación General')], max_length=20)),
                ('motivo', models.TextField()),
                ('dias_vacaciones_pendientes', models.IntegerField(default=0)),
                ('monto_vacaciones_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('monto_antiguedad_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('monto_utilidades_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('monto_prestaciones_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('otros_pagos_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_liquidacion_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-fecha_liquidacion', 'id_empleado'],
            },
        ),
    ]
