# Generated by Django 5.1.5 on 2025-11-19 17:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0002_remove_tipodejornada_horas_semanales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioLabor',
            fields=[
                ('id_cambio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Cambio')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo o Razón del Cambio')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_labor', to='secundario.empleado')),
                ('labor_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_previa', to='secundario.labor')),
                ('labor_nueva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_actual', to='secundario.labor')),
            ],
            options={
                'verbose_name': 'Registro de Cambio de Labor',
                'verbose_name_plural': 'Historial de Cambios de Labor',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
