# Generated by Django 5.1.5 on 2025-04-04 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0002_alter_sueldo_id_empleado_alter_sueldo_id_jornada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sueldo',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='id_jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.tipodejornada', verbose_name='Jornada'),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='id_tasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.tasa', verbose_name='Tasa'),
        ),
    ]
