# Generated by Django 5.1.5 on 2025-11-19 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0003_cambiolabor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonoExtra',
            fields=[
                ('id_bono', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=150, verbose_name='Concepto del Bono')),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (Bs)')),
                ('fecha_aplicacion', models.DateField(verbose_name='Fecha de Aplicación')),
                ('pagado_en_nomina', models.BooleanField(default=False, verbose_name='Pagado en Nómina')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos_recibidos', to='secundario.empleado')),
            ],
            options={
                'verbose_name': 'Asignación/Bono Extra',
                'verbose_name_plural': 'Asignaciones/Bonos Extras',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
