# Generated by Django 5.1.5 on 2025-07-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0003_liquidacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liquidacion',
        ),
    ]
