# Generated by Django 5.1.5 on 2025-07-24 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0004_delete_liquidacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id_liquidacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_egreso', models.DateField(verbose_name='Fecha de Egreso')),
                ('motivo_egreso', models.CharField(choices=[('renuncia', 'Renuncia'), ('despido_justificado', 'Despido Justificado'), ('despido_injustificado', 'Despido Injustificado'), ('mutuo_acuerdo', 'Mutuo Acuerdo'), ('fin_contrato', 'Fin de Contrato'), ('jubilacion', 'Jubilación'), ('fallecimiento', 'Fallecimiento')], max_length=50, verbose_name='Motivo de Egreso')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('salario_mensual_base_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Salario Mensual Base (Bs)')),
                ('salario_integral_diario_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Salario Integral Diario (Bs)')),
                ('antiguedad_anos', models.IntegerField(verbose_name='Antigüedad (años)')),
                ('antiguedad_dias', models.IntegerField(verbose_name='Antigüedad (días)')),
                ('prestaciones_sociales_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prestaciones Sociales (Bs)')),
                ('intereses_prestaciones_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Intereses sobre Prestaciones (Bs)')),
                ('vacaciones_no_disfrutadas_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Vacaciones No Disfrutadas (Bs)')),
                ('bono_vacacional_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Bono Vacacional Proporcional (Bs)')),
                ('utilidades_proporcionales_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Utilidades Proporcionales (Bs)')),
                ('indemnizacion_sustitutiva_preaviso_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Indemnización Sustitutiva de Preaviso (Bs)')),
                ('indemnizacion_antiguedad_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Indemnización por Antigüedad (Art. 147 LOTT) (Bs)')),
                ('total_pagar_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total a Pagar (Bs)')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-fecha_creacion', 'id_empleado'],
            },
        ),
    ]
