# Generated by Django 5.1.5 on 2025-11-19 17:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0004_bonoextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptonomina',
            name='pago_bonos_bs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pago de Bonos Extra (Bs)'),
        ),
    ]
