# Generated by Django 5.1.5 on 2025-07-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0005_liquidacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacionsocialacumulada',
            name='id_empleado',
        ),
        migrations.DeleteModel(
            name='Liquidacion',
        ),
        migrations.DeleteModel(
            name='PrestacionSocialAcumulada',
        ),
    ]
