# Generated by Django 5.1.5 on 2025-11-26 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0005_conceptonomina_pago_bonos_bs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeduccionPeriodica',
            fields=[
                ('id_deduccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_deduccion', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Concepto de Deducción')),
                ('tasa_semanal', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa Semanal (%)')),
                ('tasa_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa Mensual (%)')),
                ('tasa_trimestral', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa Trimestral (%)')),
                ('fecha_ultima_actualizacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Deducción Periódica',
                'verbose_name_plural': 'Deducciones Periódicas',
            },
        ),
    ]
