# Generated by Django 5.1.5 on 2025-07-24 16:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0006_remove_prestacionsocialacumulada_id_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin_relacion', models.DateField(verbose_name='Fecha de Fin de Relación Laboral')),
                ('motivo_terminacion', models.CharField(choices=[('renuncia', 'Renuncia'), ('despido_justificado', 'Despido Justificado'), ('despido_injustificado', 'Despido Injustificado'), ('mutuo_acuerdo', 'Mutuo Acuerdo'), ('otros', 'Otros')], max_length=50, verbose_name='Motivo de Terminación')),
                ('salario_normal_final', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Último Salario Normal')),
                ('salario_integral_final', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Último Salario Integral')),
                ('monto_prestaciones_garantia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Garantía de Prestaciones Sociales')),
                ('monto_intereses_prestaciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Intereses de Prestaciones')),
                ('monto_prestaciones_retroactivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Prestaciones (Cálculo Retroactivo)')),
                ('monto_prestaciones_a_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Prestaciones a Pagar')),
                ('anticipos_prestaciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Anticipos de Prestaciones Descontados')),
                ('dias_vacaciones_pendientes', models.IntegerField(default=0, verbose_name='Días Vacaciones Pendientes')),
                ('monto_vacaciones_pendientes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Vacaciones Pendientes')),
                ('dias_bono_vacacional_pendiente', models.IntegerField(default=0, verbose_name='Días Bono Vacacional Pendientes')),
                ('monto_bono_vacacional_pendiente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Bono Vacacional Pendiente')),
                ('dias_utilidades_pendientes', models.IntegerField(default=0, verbose_name='Días Utilidades Pendientes')),
                ('monto_utilidades_pendientes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Utilidades Pendientes')),
                ('monto_indemnizacion_despido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Indemnización por Despido Injustificado')),
                ('monto_preaviso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto de Preaviso')),
                ('total_liquidacion', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total de Liquidación')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='secundario.empleado')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-fecha_fin_relacion'],
            },
        ),
        migrations.CreateModel(
            name='PrestacionSocialAcumulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateField(default=django.utils.timezone.now)),
                ('monto_acumulado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('intereses_acumulados', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('dias_acumulados', models.IntegerField(default=0)),
                ('salario_integral_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones_acumuladas', to='secundario.empleado')),
            ],
            options={
                'verbose_name': 'Prestación Social Acumulada',
                'verbose_name_plural': 'Prestaciones Sociales Acumuladas',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
