# Generated by Django 5.1.5 on 2025-11-26 21:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0006_deduccionperiodica'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeduccionNomina',
            fields=[
                ('id_deduccion_nomina', models.AutoField(primary_key=True, serialize=False)),
                ('monto_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Deducido (Bs)')),
                ('id_concepto_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otras_deducciones', to='secundario.conceptonomina', verbose_name='Concepto de Nómina')),
                ('id_deduccion_periodica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secundario.deduccionperiodica', verbose_name='Tipo de Deducción Periódica')),
            ],
            options={
                'verbose_name': 'Deducción Dinámica de Nómina',
                'verbose_name_plural': 'Deducciones Dinámicas de Nómina',
                'unique_together': {('id_concepto_nomina', 'id_deduccion_periodica')},
            },
        ),
    ]
