# Generated by Django 5.1.5 on 2025-11-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0007_deduccionnomina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeduccionNomina',
        ),
        migrations.DeleteModel(
            name='DeduccionPeriodica',
        ),
    ]
