# Generated by Django 5.1.5 on 2025-07-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0008_nomina_pago_inasistencias_bs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='pago_prestaciones_bs',
        ),
    ]
