# Generated by Django 5.1.5 on 2025-11-26 21:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0008_delete_deduccionnomina_delete_deduccionperiodica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametrosnomina',
            options={'verbose_name': 'Concepto/Regla de Nómina', 'verbose_name_plural': 'Conceptos/Reglas de Nómina'},
        ),
        migrations.RemoveField(
            model_name='parametrosnomina',
            name='factor_calculo_cestaticket',
        ),
        migrations.RemoveField(
            model_name='parametrosnomina',
            name='tasa_faov',
        ),
        migrations.RemoveField(
            model_name='parametrosnomina',
            name='tasa_ivss',
        ),
        migrations.RemoveField(
            model_name='parametrosnomina',
            name='tasa_rpe',
        ),
        migrations.RemoveField(
            model_name='parametrosnomina',
            name='unidad_tributaria_valor',
        ),
        migrations.AddField(
            model_name='parametrosnomina',
            name='es_concepto_fijo',
            field=models.BooleanField(default=False, verbose_name='Es Tasa/Factor Fijo Global (IVSS, UT, Cesta)'),
        ),
        migrations.AddField(
            model_name='parametrosnomina',
            name='monto_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Monto Fijo (Bs) / Valor UT'),
        ),
        migrations.AddField(
            model_name='parametrosnomina',
            name='nombre',
            field=models.CharField(default=2, max_length=150, unique=True, verbose_name='Nombre del Concepto/Regla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosnomina',
            name='periodicidad',
            field=models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual'), ('UNICA', 'Única (por evento)')], default='MENSUAL', max_length=10, verbose_name='Periodicidad de Aplicación'),
        ),
        migrations.AddField(
            model_name='parametrosnomina',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=5, null=True, verbose_name='Porcentaje (Ej: Tasa IVSS)'),
        ),
        migrations.AddField(
            model_name='parametrosnomina',
            name='tipo',
            field=models.CharField(choices=[('ASIGNACION', 'Asignación'), ('DEDUCCION', 'Deducción')], default='ASIGNACION', max_length=10, verbose_name='Tipo de Concepto'),
        ),
        migrations.AlterField(
            model_name='parametrosnomina',
            name='id_parametro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
