# Generated by Django 5.1.5 on 2025-11-26 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0009_alter_parametrosnomina_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleConceptoNomina',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_concepto', models.CharField(max_length=150, verbose_name='Nombre del Concepto')),
                ('tipo_concepto', models.CharField(max_length=10, verbose_name='Tipo (Asignación/Deducción)')),
                ('monto_calculado_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Calculado (Bs)')),
                ('id_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_personalizados', to='secundario.nomina', verbose_name='Nómina')),
                ('id_regla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secundario.parametrosnomina', verbose_name='Regla Aplicada')),
            ],
            options={
                'verbose_name': 'Detalle de Concepto Personalizado',
                'verbose_name_plural': 'Detalles de Conceptos Personalizados',
                'unique_together': {('id_nomina', 'id_regla')},
            },
        ),
    ]
