# Generated by Django 5.1.5 on 2025-07-25 16:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0009_remove_nomina_pago_prestaciones_bs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('monto_total_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Total del Préstamo (Bs)')),
                ('monto_pendiente_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Pendiente (Bs)')),
                ('cuotas_restantes', models.IntegerField(default=0, verbose_name='Cuotas Restantes')),
                ('monto_cuota_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto por Cuota (Bs)')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
