# Generated by Django 5.1.5 on 2025-07-25 16:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0010_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='pago_prestamo_bs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Deducción Préstamo (Bs)'),
        ),
    ]
