# Generated by Django 5.1.5 on 2025-11-27 01:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0010_detalleconceptonomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptonomina',
            name='inces_bs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Deducción INCES (Bs)'),
        ),
    ]
