# Generated by Django 5.1.5 on 2025-11-26 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0011_conceptonomina_inces_bs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleconceptonomina',
            name='id_regla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secundario.parametrosnomina'),
        ),
    ]
