# Generated by Django 5.1.5 on 2025-07-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0011_nomina_pago_prestamo_bs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='tipo_periodo',
            field=models.CharField(choices=[('semanal', 'Semanal')], default='quincenal', max_length=10),
        ),
    ]
