# Generated by Django 5.1.5 on 2025-11-26 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0012_alter_detalleconceptonomina_id_regla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleconceptonomina',
            name='id_regla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secundario.parametrosnomina'),
        ),
    ]
