# Generated by Django 5.1.5 on 2025-11-27 05:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0013_alter_detalleconceptonomina_id_regla'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptonomina',
            name='pago_recargo_nocturno_bs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pago Recargo Nocturno (Bs)'),
        ),
    ]
