# Generated by Django 5.1.5 on 2025-08-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0013_alter_nomina_tipo_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='motivo_terminacion',
            field=models.CharField(choices=[('renuncia', 'Renuncia'), ('despido_justificado', 'Despido Justificado'), ('despido_injustificado', 'Despido Injustificado'), ('mutuo_acuerdo', 'Mutuo Acuerdo')], max_length=50, verbose_name='Motivo de Terminación'),
        ),
    ]
