# Generated by Django 5.1.5 on 2025-11-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0014_conceptonomina_pago_recargo_nocturno_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosnomina',
            name='monto_fijo_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Monto en USD (ej: cestaticket 40 USD)', max_digits=12, null=True),
        ),
    ]
