# Generated by Django 5.1.5 on 2025-08-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0014_alter_liquidacion_motivo_terminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='motivo_terminacion',
            field=models.CharField(choices=[('renuncia', 'Renuncia'), ('despido_justificado', 'Despido Justificado'), ('despido_injustificado', 'Despido Injustificado')], max_length=50, verbose_name='Motivo de Terminación'),
        ),
    ]
