# Generated by Django 5.1.5 on 2025-11-29 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0015_parametrosnomina_monto_fijo_usd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoSuperuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_firmado', models.CharField(max_length=255, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Para auditoría 2025, para nuevo admin', max_length=100)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Códigos de Superusuario',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
