# Generated by Django 5.1.5 on 2025-11-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0016_codigosuperuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_superuser_hash', models.CharField(max_length=128, unique=True)),
                ('descripcion', models.CharField(default='Código maestro permanente para crear superusuarios', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.DeleteModel(
            name='CodigoSuperuser',
        ),
    ]
