# Generated by Django 5.1.5 on 2025-08-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0016_alter_liquidacion_motivo_terminacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='dias_vacaciones_otorgados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Días de Vacaciones Otorgados (si aplica)'),
        ),
    ]
