# Generated by Django 5.1.5 on 2025-08-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0017_liquidacion_dias_vacaciones_otorgados'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='fecha_regreso_trabajo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Regreso al Trabajo'),
        ),
    ]
