# Generated by Django 5.1.5 on 2025-11-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0017_configuracionsistema_delete_codigosuperuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='configurado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='codigo_superuser_hash',
            field=models.CharField(blank=True, help_text='Hash del código maestro (Argon2). Nunca en texto plano.', max_length=255),
        ),
    ]
