# Generated by Django 5.1.5 on 2025-11-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0018_remove_configuracionsistema_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoActivacionSuperuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(blank=True, max_length=255)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activado', models.BooleanField(default=False, help_text='Marcado cuando ya se configuró el código')),
            ],
            options={
                'verbose_name': 'Código de Activación de Superusuarios',
                'verbose_name_plural': 'Código de Activación de Superusuarios',
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracionSistema',
        ),
    ]
