# Generated by Django 5.1.5 on 2025-08-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0018_liquidacion_fecha_regreso_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='tipo_periodo',
            field=models.CharField(choices=[('semanal', 'Semanal')], default='quincenal', max_length=10),
        ),
    ]
