# Generated by Django 5.1.5 on 2025-11-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0019_codigoactivacionsuperuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoactivacionsuperuser',
            name='codigo_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='superuser_code'),
        ),
    ]
