# Generated by Django 5.1.5 on 2025-08-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0019_alter_nomina_tipo_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='tipo_periodo',
            field=models.CharField(choices=[('semanal', 'Semanal')], default='semanal', max_length=10),
        ),
    ]
