# Generated by Django 5.1.5 on 2025-12-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0020_alter_codigoactivacionsuperuser_codigo_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='codigoactivacionsuperuser',
            name='activado',
            field=models.BooleanField(default=False, help_text='Se marca cuando ya se usó por primera vez'),
        ),
        migrations.AlterField(
            model_name='codigoactivacionsuperuser',
            name='codigo_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='Código (hash)'),
        ),
    ]
