# Generated by Django 5.1.5 on 2025-10-31 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0020_alter_nomina_tipo_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ASIGNACION', 'Asignación'), ('DEDUCCION', 'Deducción')], max_length=12)),
                ('es_por_dias', models.BooleanField(default=False, help_text='Ej: Salario base')),
                ('es_cuota_fija', models.BooleanField(default=False, help_text='Ej: Cestaticket')),
                ('valor_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('formula', models.TextField(blank=True, help_text='Ej: salario * 0.04 (IVSS)')),
            ],
        ),
        migrations.CreateModel(
            name='NominaNueva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PN', 'Prenómina'), ('CC', 'Nómina Cerrada')], default='PN', max_length=2)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.empleado')),
                ('sueldo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secundario.sueldo')),
            ],
        ),
        migrations.CreateModel(
            name='ItemNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unidad', models.CharField(default='DÍAS', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secundario.conceptonomina')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='secundario.nominanueva')),
            ],
        ),
    ]
